branch-defaults:
  default:
    environment: franquicias-vpc-env
environment-defaults:
  franquicias-vpc-env:
    branch: null
    repository: null
global:
  application_name: franquicias-api
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
